gitHooksPath: .github/hooks

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-git-hooks.cjs
    spec: bundles/@yarnpkg/plugin-git-hooks.js

yarnPath: .yarn/releases/yarn-3.5.0.cjs
